---
name: "Setup Malbolge"
author: Yevhen Fabizhevskyi
description: "This action installs malbolge interpreter."
branding:
  icon: terminal
  color: gray-dark
runs:
  using: "composite"
  steps:
    - name: Install malbolge
      run: |
        if ! command -v malbolge >/dev/null 2>&1; then
          if [ "${RUNNER_OS}" = "macOS" ]; then
            echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
            exit 1
          fi
          gcc src/malbolge.c -o malbolge
          echo "$GITHUB_WORKSPACE" >> "$GITHUB_PATH"
        else
          echo "::debug::$(which malbolge) is already installed"
        fi
      shell: sh
