---
name: 'Setup malbolge'
author: Yevhen Fabizhevskyi
description: 'This action installs malbolge interpreter.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - name: Fail
      uses: actions/github-script@v6
      if: ${{ runner.os != 'Linux' }}
      with:
        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
    - name: Collect info
      if: ${{ runner.os == 'Linux' }}
      id: info
      run: |
        MALBOLGE_INSTALLED=$(if command -v malbolge >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "MALBOLGE_INSTALLED=$MALBOLGE_INSTALLED" >> $GITHUB_OUTPUT
      shell: sh
    - name: Install malbolge
      if: ${{ runner.os == 'Linux' && steps.info.outputs.MALBOLGE_INSTALLED == 'false' }}
      run: |
        gcc src/malbolge.c -o malbolge
        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
      shell: sh
