---
name: 'Setup malbolge'
author: Yevhen Fabizhevskyi
description: 'This action installs malbolge interpreter.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'malbolge version.'
    required: false
    default: '0.2'
runs:
  using: 'composite'
  steps:
    - name: Fail
      uses: actions/github-script@v6
      if: ${{ runner.os != 'Linux' }}
      with:
        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
    - name: Collect info
      if: ${{ runner.os == 'Linux' }}
      id: info
      run: |
        MALBOLGE_INSTALLED=$(if command -v malbolge >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "MALBOLGE_INSTALLED=$MALBOLGE_INSTALLED" >> $GITHUB_OUTPUT
        malbolge_path="$GITHUB_WORKSPACE/malbolge"
        mkdir -p $malbolge_path
        echo "MALBOLGE_PATH=$malbolge_path" >> $GITHUB_OUTPUT
      shell: sh
    - name: Install malbolge
      if: ${{ runner.os == 'Linux' && steps.info.outputs.MALBOLGE_INSTALLED == 'false' }}
      run: |
        wget -c https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/malbolge/${{ inputs.version }}-0ubuntu1/malbolge_${{ inputs.version }}.orig.tar.gz -O - | tar -xz
        echo "${{ steps.info.outputs.MALBOLGE_PATH }}" >> $GITHUB_PATH
        echo "ls -A:"
        ls -A
      shell: sh
      working-directory: ${{ steps.info.outputs.MALBOLGE_PATH }}
