---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - src/**
      - action.yml
  schedule:
    # Every Friday at 09:00 JST
    - cron: "0 0 * * 5"
  workflow_dispatch: {}

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
      - name: Setup malbolge
        id: setup-malbolge
        uses: ./
      - name: Test action completion
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "malbolge should be installed" \
            "${{ steps.setup-malbolge.outputs.installed }}" \
            "true"
      - name: Validate command
        run: |
          [ "$(malbolge hello-world.mal)" = "Hello, world." ] || exit 1;
  test-force:
    name: Test force
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        force: ["true", "false"]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
      - name: Setup malbolge 1
        id: setup-malbolge-1
        uses: ./
      - name: Setup malbolge 2
        id: setup-malbolge-2
        uses: ./
        with:
          force: ${{ matrix.force }}
      - name: Test action completion
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "Wrong \"installed\" output from setup-malbolge-1" \
            "${{ steps.setup-malbolge-1.outputs.installed }}" \
            "true"
          test_equal "Wrong \"installed\" output from setup-malbolge-2" \
            "${{ steps.setup-malbolge-2.outputs.installed }}" \
            "${{ matrix.force }}"
