---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup malbolge
        uses: ./
      - name: Run script
        run: |
          [ "$(malbolge hello-world.mal)" = "Hello, world." ] || exit 1;
